<?php

/**
* @file
* Module that will allow a user to submit their max reps
* for various exercises. It will also display the data after
* submission by the user.
*/


/**
* Implements hook_menu().
*
* Set up URL so building a workout
* can be chosen right from the menu.
*/

function max_reps_menu() {

  $items = array();
  $items['max_reps'] = array(
    'title' => 'Max Reps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('max_reps'),
    'access callback' => TRUE,
	'file' => 'max_reps.inc',
    'type' => MENU_NORMAL_ITEM, 
  );
  return $items;
}


/**
 * Implements hook_theme().
 */
function max_reps_theme() {
  return array(
    'max_reps' => array(
      'render element' => 'form',
      'template' => 'max-reps',
    ),
  );
}

/**
 * Assign the elements of the form to variables so
 * the themer can use those values to control how the
 * form elements are displayed, or alternatively
 * displaying the whole form as constructed above.
 */
function template_preprocess_max_reps(&$variables) {

	$variables['max_reps'] = array();
	$hidden = array();
	// Provide variables named after form keys so themers can print each element
	//independently.
	foreach (element_children($variables['form']) as $key) {
		$type = $variables['form'][$key]['#type'];
		if ($type == 'hidden' || $type == 'token') {
			$hidden[] = drupal_render($variables['form'][$key]);
		}
		else {
			$variables['max_reps'][$key] = drupal_render($variables['form'][$key]);
		}
	}
	// Hidden form elements have no value to themers. No need for separation.
	$variables['max_reps']['hidden'] = implode($hidden);
	// Collect all form elements to make it easier to print the whole form.
	$variables['max_reps_form'] = implode($variables['max_reps']);
}